#pragma once

#include "utils/setup.h"
#include "utils/log.h"
#include "utils/mathdefs.h"
#include "utils/utils.h"
#include "utils/dbg_gui.h"

#include "core/window.h"
#include "core/input.h"
#include "core/audio.h"
#include "core/gui.h"
#include "core/selection.h"

#include "core/text.h"
#include "core/quad.h"
#include "core/shader.h"
#include "core/texture.h"
#include "core/palette.h"
#include "core/renderer.h"
#include "core/framebuffer.h"
#include "core/sprite.h"
#include "core/cursor.h"

#include "game/app.h"
#include "game/resources.h"
#include "game/camera.h"
#include "game/level.h"
#include "game/faction.h"
#include "game/player_controller.h"
#include "game/controllers.h"
#include "game/gameobject.h"
#include "game/object_data.h"
#include "game/command.h"
#include "game/config.h"

#include "utils/generator.h"
#include "utils/ring_buffer.hpp"
#include "utils/pool.hpp"
#include "utils/randomness.h"
